// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd707crfnMB54ySn7ZAS2-nbqO7XqrliE',
    appId: '1:179677512297:web:56759b140c392fe6c7d8f8',
    messagingSenderId: '179677512297',
    projectId: 'project-hector-b8613',
    authDomain: 'project-hector-b8613.firebaseapp.com',
    storageBucket: 'project-hector-b8613.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzAufeDTETPvVM4ZxAwmPSIflccyBFwR4',
    appId: '1:179677512297:android:51baea6fb7ba1114c7d8f8',
    messagingSenderId: '179677512297',
    projectId: 'project-hector-b8613',
    storageBucket: 'project-hector-b8613.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAN5qkXYTE0E7SaIOMgQL4sb0kZuiIkLo',
    appId: '1:179677512297:ios:ee804879f0998f8ac7d8f8',
    messagingSenderId: '179677512297',
    projectId: 'project-hector-b8613',
    storageBucket: 'project-hector-b8613.appspot.com',
    iosBundleId: 'com.example.projectHector',
  );
}
